<?php

/*
 * Game options
 */
define('OPTION_BEGINNER', 102);
define('OPTION_BEGINNER_ENABLED', 0);
define('OPTION_BEGINNER_DISABLED', 1);

define('OPTION_ADDITIONAL_SPACES', 103);
define('OPTION_ADDITIONAL_SPACES_DISABLED', 0);
define('OPTION_ADDITIONAL_SPACES_ENABLED', 1);

define('OPTION_DECK_A', 104);
define('OPTION_DECK_B', 105);
define('OPTION_DECK_ENABLED', 0);
define('OPTION_DECK_DISABLED', 1);
define('OPTION_DECK_MAPPING', [
  'A' => OPTION_DECK_A,
  'B' => OPTION_DECK_B,
]);

define('OPTION_DRAFT', 106);
define('OPTION_DRAFT_SOLO', 108);
define('OPTION_DRAFT_DISABLED', 0);
define('OPTION_PICK_7_OUT_OF_10', 1);
define('OPTION_DRAFT_7_SIMULTANEOUS', 2);
define('OPTION_DRAFT_8_SIMULTANEOUS', 3);
define('OPTION_DRAFT_9_SIMULTANEOUS', 4);
define('OPTION_DRAFT_10_SIMULTANEOUS', 5);
define('OPTION_DRAFT_7_OCCUPATIONS', 6);
define('OPTION_DRAFT_8_OCCUPATIONS', 7);
define('OPTION_DRAFT_9_OCCUPATIONS', 8);
define('OPTION_DRAFT_10_OCCUPATIONS', 9);
define('OPTION_DRAFT_7_MINORS', 10);
define('OPTION_DRAFT_8_MINORS', 11);
define('OPTION_DRAFT_9_MINORS', 12);
define('OPTION_DRAFT_10_MINORS', 13);
define('OPTION_DRAFT_FREE', 14);

define('ONE_SHOT', 1);
define('SIMULTANEOUS', 2);
define('OCCUPATION_FIRST', 3);
define('MINOR_FIRST', 4);

define('OPTION_SCORING', 107);
define('OPTION_SCORING_ENABLED', 0);
define('OPTION_SCORING_DISABLED', 1);

/*
 * User preferences
 */
define('OPTION_AUTOPAY_HARVEST', 102);
define('OPTION_AUTOPAY_HARVEST_ENABLED', 0);
define('OPTION_AUTOPAY_HARVEST_DISABLED', 1);

define('OPTION_CONFIRM', 103);
define('OPTION_CONFIRM_DISABLED', 0);
define('OPTION_CONFIRM_TIMER', 1);
define('OPTION_CONFIRM_ENABLED', 2);

define('OPTION_COLORBLIND', 104);
define('OPTION_COLORBLIND_OFF', 0);
define('OPTION_COLORBLIND_ON', 1);

define('OPTION_FONT_DOMINICAN', 105);
define('OPTION_FONT_DOMINICAN_ON', 0);
define('OPTION_FONT_DOMINICAN_OFF', 1);

define('OPTION_SMART_REORGANIZE', 106);
define('OPTION_SMART_REORGANIZE_ON', 0);
define('OPTION_SMART_REORGANIZE_OFF', 1);

define('OPTION_PLAYER_BOARDS', 107);
define('OPTION_PLAYER_BOARDS_BOTTOM', 0);
define('OPTION_PLAYER_BOARDS_RIGHT', 1);

define('OPTION_DISPLAY_CARDS', 108);
define('OPTION_DISPLAY_CARDS_MODAL', 0);
define('OPTION_DISPLAY_CARDS_BOARD', 1);
define('OPTION_DISPLAY_CARDS_BOTTOM', 2);

/*
 * State constants
 */
define('ST_GAME_SETUP', 1);

define('ST_START', 2);

define('ST_PRE_END_OF_GAME', 98);
define('ST_END_GAME', 99);
